In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr) #[1 2 3 4 5] no commas
print("Type", type(arr))

Array: [1 2 3 4 5]
Type <class 'numpy.ndarray'>


In [ ]:
# Addition of two arrays

arr_1 = np.array([10, 20, 30, 40, 50])

arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 + arr_2
print("Sum of two arrays:", arr_3) #[11 22 33 44 55]

Sum of two arrays: [11 22 33 44 55]


In [7]:
# Subtraction of two arrays

arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 - arr_2
print("Difference of two arrays:", arr_3) #[ 9 18 27 36 45]

Difference of two arrays: [ 9 18 27 36 45]


In [ ]:
# Multiplication of two arrays

arr_1 = np.array([10, 20, 30, 40, 50])
arr_2 = np.array([1, 2, 3, 4, 5])

arr_3 = arr_1 * arr_2
print("Product of two arrays:", arr_3) #[ 10  40  90 160 250]

Product of two arrays: [ 10  40  90 160 250]


In [11]:
# Division of two arrays

arr_1 = np.array([10, 20, 20, 40, 50])
arr_2 = np.array([2,7,3,8,5])

arr_3 = arr_1 / arr_2
print("Division of two arrays:", arr_3) #[5. 2.85714286 6.66666667 5. 10.]

Division of two arrays: [ 5.          2.85714286  6.66666667  5.         10.        ]


In [ ]:
#Sum of all elements in an array\

arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)

print("Sum of all elements in the array:", total) #15

Sum of all elements in the array: 15


In [ ]:
#mean of array elements

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)

print("Mean of array elements:", mean_value) #3.0 (1+2+3+4+5)/5 = 15/5 =3.0

Mean of array elements: 3.0


In [14]:
#maximum value in an array

arr = np.array([1, 2, 3, 4, 5])
max_value = np.max(arr)

print("Maximum value in the array:", max_value) #5

Maximum value in the array: 5


In [15]:
#minimum value in an array

arr = np.array([1, 2, 3, 4, 5])
min_value = np.min(arr)

print("Minimum value in the array:", min_value) #1

Minimum value in the array: 1


In [16]:
#Square root of each element in the array

arr = np.array([1, 4, 9, 16, 25])
sqrt_arr = np.sqrt(arr)

print("Square root of each element in the array:", sqrt_arr) #[1. 2. 3. 4. 5.]

Square root of each element in the array: [1. 2. 3. 4. 5.]


In [ ]:
#Creating a 2D array

arr = np.array([[9, 8 , 5], [10, 20 ,21]])
print("2D Array:\n", arr)

2D Array:
 [[ 9  8  5]
 [10 20 21]]


In [ ]:
#Shape of the array

arr = np.array([[9, 8 , 5], [10, 20 ,21]])
print("Shape of the array:", arr.shape) #(2, 3) 2 rows and 3 columns ( this is a tuple(tuple is immutable))

Shape of the array: (2, 3)


In [ ]:
#Size of the array

arr = np.array([[9, 8 , 5], [10, 20 ,21]])
print("Size of the array:", arr.size) #6 ( total individual number of elements in the array)

Size of the array: 6


In [21]:
#ndim (number of dimensions) of the array

arr = np.array([[9, 8 , 5], [10, 20 ,21]])
print("Number of dimensions of the array:", arr.ndim) #2 ( 2D array)

Number of dimensions of the array: 2


In [ ]:
#define a 3d array 
arr = np.array([[[1, 2], 
                 [4, 5],
                 [5, 7]], 
                 
                 [[7, 8], 
                 [10, 11],
                 [12, 14]], 
                 
                 [[2, 6],
                  [3, 5],
                  [7, 8]]])

print("3D Array:\n", arr)

print("\nShape of the 3D array:", arr.shape) #(3, 3, 2) 3 blocks, each block has 3 rows and 2 columns
print("Number of dimensions of the 3D array:", arr.ndim) #3

3D Array:
 [[[ 1  2]
  [ 4  5]
  [ 5  7]]

 [[ 7  8]
  [10 11]
  [12 14]]

 [[ 2  6]
  [ 3  5]
  [ 7  8]]]

Shape of the 3D array: (3, 3, 2)
Number of dimensions of the 3D array: 3


In [ ]:
#Index 

arr = np.array([[9 ,8, 5], [10, 20, 21]])

print ("Element at row 1, column 2:", arr[1, 2]) #21 (indexing starts from 0) --> recomended way of indexing

print ("Element at row 1, column 2:", arr[1][2]) #21 (alternative way of indexing) --> not recomended

Element at row 1, column 2: 21


In [ ]:
#Condition 

arr = np.array([10, 20, 15, 18, 14, 26])

condition = arr > 15

print("Condition (elements greater than 15):", condition) #[False  True False  True False  True]

filtered_arr = arr[condition] #filtering elements based on condition
#filtered_arr = arr[arr > 15] #directly filtering elements based on condition
print("Filtered array (elements greater than 15):", filtered_arr) #[20 18 26]

Condition (elements greater than 15): [False  True False  True False  True]
Filtered array (elements greater than 15): [20 18 26]


In [ ]:
#(i)greater than 10 or less than 5
#(ii) not equal to 15
arr = np.array([
    [12, 5, 7, 20],
    [3, 15, 8, 2,],
    [10, 25, 6, 18],
    [4, 11, 30, 9]
])

filtered_arr = arr[((arr>10) | (arr<5)) & (arr != 15) ] #filtering even numbers

print("Filtered array (elements greater than 10 or less than 5 and not equal to 15):", filtered_arr) #[12 20 3 2 25 18 4 11 30]

Filtered array (elements greater than 10 or less than 5 and not equal to 15): [12 20  3  2 25 18  4 11 30]


In [ ]:
#np.zeroes

arr = np.zeros((2, 3)) #2 rows and 3 columns

print("Array of zeros:\n", arr)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
#np.full

arr =np.full((3, 4), 7) #3 rows and 4 columns, all elements are 7
print("Array filled with 7s:\n", arr)

Array filled with 7s:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
#np.empty (creates an array without initializing the entries, the values will be random and depend on the state of the memory(Garbage values of the memory ))

arr = np.empty((3, 2)) #3 rows and 2 columns
print("Empty array (uninitialized values):\n", arr)
#purpose of np.empty is to create an array quickly when the initial values are not important, and you plan to fill in the values later. This can be useful for performance optimization in scenarios where you need to create large arrays and want to avoid the overhead of initializing all elements to a specific value.
b

Empty array (uninitialized values):
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
import pandas as pd

data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

df = pd.DataFrame(data)
print("DataFrame:\n", df)
print("\nType of df:", type(df)) #(0,1,2,3 are row labels)
#By default row labels and row indexes are same , but we can change row labels as per our requirement

DataFrame:
     name  age
0   John   25
1  Alice   30
2    Bob   22
3    Eva   28

Type of df: <class 'pandas.core.frame.DataFrame'>


In [ ]:
#Access using labels(loc)

data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

#loc function is used to access rows and columns by labels
print(df.loc[2]) #accessing row at  label 2

name    Bob
age      22
Name: 2, dtype: object


In [52]:
#access using row labels and column labels

data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

print(df.loc[2, "age"]) #accessing element at row label 2 and column label 'age' ([row, column])

22


In [53]:
#Access using indexes(iloc)
data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

print(df.iloc[2]) #accessing row at index 2

name    Bob
age      22
Name: 2, dtype: object


In [54]:
#using row and column indexes

data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

df = pd.DataFrame(data)
print(df.iloc[2, 1]) #accessing element at row index 2 and column index 1 ([row, column])

22


In [55]:
#Manual labeling of rows

data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

df = pd.DataFrame(data, index=["a", "b", "c", "d"]) #manual labeling of rows
print(df)

    name  age
a   John   25
b  Alice   30
c    Bob   22
d    Eva   28


In [64]:
data ={
    "name" : ["John", "Alice", "Bob", "Eva"],
    "age" : [25, 30, 22, 28],
}

df = pd.DataFrame(data, index=["day1", "day2", "day3", "day4"]) #manual labeling of rows
print(df)
print(df.shape)

#day2
print("\n", df.loc["day2"]) #accessing row at label 'day2'

#day1, day3 
print("\n", df.loc[["day1", "day3"]]) #accessing rows at labels 'day1' and 'day3' (need another [] for multiple rows/pass as a list)


       name  age
day1   John   25
day2  Alice   30
day3    Bob   22
day4    Eva   28
(4, 2)

 name    Alice
age        30
Name: day2, dtype: object

       name  age
day1  John   25
day3   Bob   22


In [ ]:
#Accessing specific column
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data, index= ['day1', 'day2', 'day3'])
print(df)
print('_ _ _ _ _ _ _ _ _ _ _ _ _')

print(df['calories'])

      calories  duration
day1       420        50
day2       380        40
day3       390        45
_ _ _ _ _ _ _ _ _ _ _ _ _
day1    420
day2    380
day3    390
Name: calories, dtype: int64


In [70]:
#df.size (total number of elements in the DataFrame)

data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data, index= ['day1', 'day2', 'day3'])
print("DataFrame:\n", df)
print("\nTotal number of elements in the DataFrame:", df.size) #6 (3 rows * 2 columns)

print("\nValues in the DataFrame:\n", df.values) # this values of the DataFrame as a 2D numpy array according to the shape of the DataFrame
#Type of df.values
print("\nType of df.values:", type(df.values)) #<class 'numpy.ndarray'>


DataFrame:
       calories  duration
day1       420        50
day2       380        40
day3       390        45

Total number of elements in the DataFrame: 6

Values in the DataFrame:
 [[420  50]
 [380  40]
 [390  45]]

Type of df.values: <class 'numpy.ndarray'>


In [ ]:
#Row count of the DataFrame

#Method 1: Using len()
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df = pd.DataFrame(data)
print("Row count using len():", len(df)) #3 # len() return the number of rows in the DataFrame

#Method 2: Using shape attribute
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df = pd.DataFrame(data)
print("Row count using shape attribute:", df.shape[0]) #3 #.shape(0) work as tuple where first element is row count and second element is column count
#df.shape --> (3, 2)

Row count using len(): 3
Row count using shape attribute: 2


In [ ]:
#Address the last row
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df = pd.DataFrame(data)
#iloc use to access rows and columns by index
print(df.iloc[-1]) #accessing last row using negative indexing [row index, all columns]

calories    390
duration     45
Name: 2, dtype: int64


In [ ]:
#.columns -> to get the column labels of the DataFrame

data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data)
print(df.columns) #use to get the column labels of the DataFrame and it returns an Index object
print(list(df.columns))

Index(['calories', 'duration'], dtype='object')
['calories', 'duration']


In [78]:
#Add a new column to the DataFrame
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}

df = pd.DataFrame(data)
df['Distance'] = [5, 4, 6] #adding a new column 'Distance' to the DataFrame
print(df)

   calories  duration  Distance
0       420        50         5
1       380        40         4
2       390        45         6


In [ ]:
#Add new row to the DataFrame at the end
data = {
    'calories': [420, 380, 390],
    'duration': [50, 40, 45]
}
df = pd.DataFrame(data)
new_row = {'calories': 450, 'duration': 55}


df.loc[len(df)] = new_row #.loc use to access rows and columns by labels
#df.iloc[len(df)] = new_row #.iloc use to access rows and columns by index
#both loc(length of df) and iloc(length of df) can use  if the index and labels are same
print(df)


   calories  duration
0       420        50
1       380        40
2       390        45
3       450        55


In [ ]:
data ={
    "age" : [25, 30, 22, 28, 32],
    "Salary" : [50000, 60000, 55000, 62000, 58000],
}

df = pd.DataFrame(data)

#Sum
print(df.sum())  #use to get the sum of each numerical column

#Mean
print("\n",df.mean()) #use to get the mean of each numerical column

#describe
print("\n",df.describe()) #use to get the statistical summary of the DataFrame

#std --> standard deviation (in simple terms, it measures how spread out the numbers are in a dataset) ex-ample: if the ages are 22, 23, 24, 25, 26, the standard deviation is low because the ages are close to the mean (24). But if the ages are 10, 20, 30, 40, 50, the standard deviation is high because the ages are spread out over a wider range.
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#how to get std step by step:
#1. Calculate the mean (average) of the dataset.
#2. Subtract the mean from each data point and square the result.
#3. Calculate the average of these squared differences.
#4. Take the square root of that average. This gives you the standard deviation.

#example:
#data: 10, 12, 14, 16, 18
#mean = (10 + 12 + 14 + 16 + 18) / 5 = 14
#std = sqrt(((10-14)² + (12-14)² + (14-14)² + (16-14)² + (18-14)²) / 5) = sqrt((16 + 4 + 0 + 4 + 16) / 5) = sqrt(40 / 5) = sqrt(8) ≈ 2.83
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#order according to ascending order
#22, 25, 28, 30, 32

#25% -> 25th percentile (the value below which 25% of the data falls(First quartile/Q1))
#How to calculate 25th percentile step by step:
#1. Order the data from smallest to largest.
#2. Calculate the rank using the formula: Rank = (P/100) * (N + 1), where P is the desired percentile (25 in this case) and N is the number of data points.
#3. If the rank is an integer, the 25th percentile is the value at that position. If the rank is not an integer, interpolate between the two closest ranks to find the 25th percentile.
#Example:
#data: 22, 25, 28, 30, 32
#N = 5 (number of data points)
#Rank = (25/100) * (5 + 1) = 1.5
#Since the rank is 1.5, we take the average of the values at positions 1 and 2:
#25th percentile = (22 + 25) / 2 = 23.5
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#50% -> median (the middle value of the dataset(median/Q2))

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#75% -> 75th percentile (the value below which 75% of the data falls(Third quartile/Q3))
#How to calculate 75th percentile step by step:
#Example:
#data: 22, 25, 28, 30, 32
#N = 5 (number of data points)  
#Rank = (75/100) * (5 + 1) = 4.5
#Since the rank is 4.5, we take the average of the values at positions 4 and 5:
#75th percentile = (30 + 32) / 2 = 31.0
#but 30 is the 75th percentile in pandas because pandas uses a different method for calculating percentiles which may lead to slightly different results compared to manual calculations.
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

age          137
Salary    285000
dtype: int64

 age          27.4
Salary    57000.0
dtype: float64

              age       Salary
count   5.000000      5.00000
mean   27.400000  57000.00000
std     3.974921   4690.41576
min    22.000000  50000.00000
25%    25.000000  55000.00000
50%    28.000000  58000.00000
75%    30.000000  60000.00000
max    32.000000  62000.00000


In [ ]:
#Filtering rows based on condition
data ={
    "age" : [25, 30, 22, 28, 32],
    "Salary" : [50000, 60000, 55000, 62000, 58000],
}

df = pd.DataFrame(data)
print(df['age']>30 , "\n") #
print(df[df['age']>30],"\n") #filtering rows where age is greater than 30

#type of filtered DataFrame
print(type([df['age']>30])) #list
print(type(df[df['age']>30])) #DataFrame

0    False
1    False
2    False
3    False
4     True
Name: age, dtype: bool 

   age  Salary
4   32   58000 

<class 'list'>
<class 'pandas.core.frame.DataFrame'>


In [105]:
#salary>75000 and age >28

data ={
    "age" : [25, 30, 22, 28, 32],
    "Salary" : [90000, 77000, 55000, 62000, 80000],
}

df = pd.DataFrame(data)

print(df[(df['Salary']>75000) & (df['age']>28)]) #filtering rows where salary is greater than 75000 and age is greater than 28

   age  Salary
1   30   77000
4   32   80000


In [ ]:


df = pd.DataFrame({
    "Product" : ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold" :[12, 50, 34, 20, 40],
    "Price" : [120000, 1500, 3500, 25000, 6000],
    "Discount" : [0.10, 0.05, 0.08, 0.12, 0.07]
})

#Final price after discount 
discounted_prices =df['Price'] * (1 - df['Discount'])
print("Final prices after discount:\n", discounted_prices)

#Total revenue (UnitSold * Final Price)
total_revenue = df['UnitSold'] * discounted_prices
print("\nTotal revenue of each product:\n", total_revenue)

#Add as new columns to the DataFrame
df['FinalPrice'] = discounted_prices
df['TotalRevenue'] = total_revenue

print("\nDataFrame with Final Price and Total Revenue:\n", df)


#products that revenue> 5000 00
high_revenue_products = df[df['TotalRevenue'] > 500000]
print("\nProducts with Total Revenue greater than 500,000:\n", high_revenue_products)

#Total revenue from all products
total_revenue_all_products = df['TotalRevenue'].sum()
print("\nTotal revenue from all products:", total_revenue_all_products)


Final prices after discount:
 0    108000.0
1      1425.0
2      3220.0
3     22000.0
4      5580.0
dtype: float64

Total revenue of each product:
 0    1296000.0
1      71250.0
2     109480.0
3     440000.0
4     223200.0
dtype: float64

DataFrame with Final Price and Total Revenue:
     Product  UnitSold   Price  Discount  FinalPrice  TotalRevenue
0    Laptop        12  120000      0.10    108000.0     1296000.0
1     Mouse        50    1500      0.05      1425.0       71250.0
2  Keyboard        34    3500      0.08      3220.0      109480.0
3   Monitor        20   25000      0.12     22000.0      440000.0
4   Headset        40    6000      0.07      5580.0      223200.0

Products with Total Revenue greater than 500,000:
   Product  UnitSold   Price  Discount  FinalPrice  TotalRevenue
0  Laptop        12  120000       0.1    108000.0     1296000.0

Total revenue from all products: 2139930.0


In [126]:
#remove rows and columns from DataFrame using .drop()
#axis=0 --> rows
#axis=1 --> columns

#Syntax:
#df.drop(labels, axis=0 or 1, inplace=False)(inplace default is False)
#inplace=True --> modifies the original DataFrame
#inplace=False --> returns a new DataFrame without modifying the original DataFrame 

#Remove Discount column
df = pd.DataFrame({
    "Product" : ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold" :[12, 50, 34, 20, 40],
    "Price" : [120000, 1500, 3500, 25000, 6000],
    "Discount" : [0.10, 0.05, 0.08, 0.12, 0.07]
})



#Remove Discount column without inplace
new_df = df.drop('Discount', axis=1) #removing 'Discount' column
print("DataFrame after removing 'Discount' column (without inplace):\n", new_df)



DataFrame after removing 'Discount' column (without inplace):
     Product  UnitSold   Price
0    Laptop        12  120000
1     Mouse        50    1500
2  Keyboard        34    3500
3   Monitor        20   25000
4   Headset        40    6000


In [127]:
#Remove row that prodect is Monitor

df = pd.DataFrame({
    "Product" : ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold" :[12, 50, 34, 20, 40],
    "Price" : [120000, 1500, 3500, 25000, 6000],
    "Discount" : [0.10, 0.05, 0.08, 0.12, 0.07]
})

#Remove row that prodect is Monitor without inplace
new_df = df.drop(df[df['Product'] == 'Monitor'].index, axis=0) #removing row where Product is 'Monitor'
print("DataFrame after removing row where Product is 'Monitor' (without inplace):\n", new_df)

DataFrame after removing row where Product is 'Monitor' (without inplace):
     Product  UnitSold   Price  Discount
0    Laptop        12  120000      0.10
1     Mouse        50    1500      0.05
2  Keyboard        34    3500      0.08
4   Headset        40    6000      0.07


In [ ]:
#Read CSV file using pandas 

df =pd.read_csv("./File_Handeling/person_data.csv")
print(df)
print(type(df))

      Name  Age         City
0    Alice   28     New York
1      Bob   34  Los Angeles
2  Charlie   25      Chicago
<class 'pandas.core.frame.DataFrame'>


In [ ]:
#Read JSON file using pandas

df = pd.read_json("./File_Handeling/my_json.json", typ='series') #typ='series' to read JSON as a Series
print(df)
print(type(df))

name          Vinod
age              30
city       New York
country         USA
dtype: object
<class 'pandas.core.series.Series'>
